apiVersion: v1
kind: Service
metadata:
  name: simple-web
  labels:
    run: simple-web
spec:
  clusterIP: 10.96.140.200
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32295
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: simple-web
  sessionAffinity: None
  type: LoadBalancer
#status:
#  loadBalancer:
#    ingress:
#    - hostname: localhost
